# Generated by Django 3.2.6 on 2021-08-26 05:34

import datetime
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full Name', models.CharField(default='', max_length=40)),
                ('Nick name', models.CharField(default='', max_length=40)),
                ('Gender', models.CharField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Other')], default='Male', max_length=10)),
                ('Date of Birth', models.DateField(default=datetime.date(1111, 11, 11))),
                ('Relation to the Family', models.CharField(choices=[(1, 'Father'), (2, 'Mother'), (3, 'Husband'), (4, 'Wife'), (5, 'Son'), (6, 'Daughter'), (7, 'Brother'), (8, 'Sister')], default='Father', max_length=10)),
                ("Father's Name", models.CharField(default='', max_length=40)),
                ("Mother's Name", models.CharField(default='', max_length=40)),
                ("Guardian's Name", models.CharField(default='', max_length=40)),
                ('Mobile Number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('Email Address', models.EmailField(default='', max_length=60)),
            ],
        ),
    ]
