# Generated by Django 3.2.6 on 2021-08-26 15:34

import datetime
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ഔദ്യോഗിക പേര് | Full Name', models.CharField(default='', max_length=100)),
                ('വിളിപ്പേരുകൾ പേര് | Aliases / Nicknames', models.CharField(default='', max_length=100)),
                ('ലിംഗഭേദം | Gender', models.CharField(choices=[(1, 'തിരഞ്ഞെടുക്കുക | Select'), (2, 'പുരുഷന്\u200d | Male'), (3, 'സ്ത്രീ | Female'), (4, 'ഭിന്ന ലിംഗം | Other')], default='തിരഞ്ഞെടുക്കുക | Select', max_length=60)),
                ('ജനന തിയതി | Date of Birth', models.DateField(default=datetime.date(1111, 11, 11))),
                ('ബന്ധം | Relation', models.CharField(choices=[(1, 'തിരഞ്ഞെടുക്കുക | Select'), (2, 'പിതാവ് | Father'), (3, 'മാതാവ് | Mother'), (4, 'ഭര്\u200dത്താവ് | Husband'), (5, 'ഭാര്യ | Wife'), (6, 'മകന്\u200d | Son'), (7, 'മകള്\u200d | Daughter'), (8, 'സഹോദരന്\u200d | Brother'), (9, 'സഹോദരി | Sister')], default='തിരഞ്ഞെടുക്കുക | Select', max_length=60)),
                ("പിതാവിന്\u200dറെ പേര് | Father's Name", models.CharField(default='', max_length=100)),
                ("മാതാവിന്\u200dറെ പേര് | Mother's Name", models.CharField(default='', max_length=100)),
                ("ഗാർഡിയന്റെ പേര് | Guardian's Name", models.CharField(default='', max_length=100)),
                ('മൊബൈല്\u200dഫോണ്\u200d നമ്പര്\u200d | Mobile Number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('ഇ മെയില്\u200d അഡ്രസ്\u200c | Email Address', models.EmailField(default='', max_length=60)),
                ('ഉയർന്ന വിദ്യാഭ്യാസം | Highest Education', models.CharField(choices=[(1, 'തെരഞ്ഞെടുക്കുക | Select'), (2, '10-ന് താഴെ | Below 10th'), (3, '10-ാം ക്ലാസ്സ് | 10th Class'), (4, '12-ാം ക്ലാസ്സ് | 12th Class'), (5, 'ഡിപ്ലോമ | Diploma'), (6, 'ബിരുദം | Graduate'), (7, 'പോസ്റ്റ് ഗ്രാജ്വേറ്റ് | Post Graduate'), (8, 'ഡോക്ടറേറ്റ് | Doctorate')], default='തെരഞ്ഞെടുക്കുക | Select', max_length=60)),
                ('വിവാഹ നില | Marital Status', models.CharField(choices=[(1, 'തെരഞ്ഞെടുക്കുക | Select'), (2, 'അവിവാഹിതന്\u200d / അവിവാഹിത | Single'), (3, 'വിവാഹിതന്\u200d / വിവാഹിത Married '), (4, 'വിധവ / വിഭാര്യന്\u200d Widow / Widower'), (5, 'Second marriage'), (6, 'Third marriage')], default='തെരഞ്ഞെടുക്കുക | Select', max_length=60)),
                ('വിവാഹ തിയതി | Date of Marriage', models.DateField(default=datetime.date(1111, 11, 11))),
                ('ജോലി / തൊഴില്\u200d | Job / Employment', models.CharField(choices=[(1, 'തെരഞ്ഞെടുക്കുക | Select'), (2, 'ബാധകമല്ല | Not applicable'), (3, 'ദിവസ കൂലി | Daily Wages'), (4, 'ശുശ്രൂഷ | Ministry'), (5, 'ഗവണ്\u200dമന്റ് ജോലി | Government service'), (6, 'പ്രൈവറ്റ് ജോലി | Private firm'), (7, 'വിദേശത്തു ജോലി | Overseas Job'), (8, 'ബിസിനസ് | Business'), (9, 'ക്യഷി | Agriculture / Plantation'), (10, 'കന്നുകാലി കൃഷി | Animal farming'), (11, 'ഡോക്ടര്\u200d | Doctor'), (12, 'നേഴ്\u200cസ് | Nurse'), (13, 'മെഡിക്കൽ (മറ്റുള്ളവ) | Medical (Others)'), (14, 'അധ്യാപകന്\u200d | Teacher'), (15, 'വക്കീൽ | Advocate'), (16, 'എൻജിനിയർ | Engineer'), (17, 'ബാങ്ക് ജോലി | Bank Employee'), (18, 'ഡ്രൈവിംഗ് | Driving Job'), (19, 'തൊഴിലുറപ്പ് | NREGA'), (20, 'സ്വയം തൊഴില്\u200d | Self Employed'), (21, 'വീട്ടമ്മ | Home maker'), (22, 'വിശ്രമ ജീവിതം | Retired'), (23, 'ജോലി ഇല്ല | Not working'), (24, 'വിദ്യാർത്ഥി | Student'), (25, 'മറ്റുള്ളവ | Others')], default='തെരഞ്ഞെടുക്കുക | Select', max_length=60)),
                ('പ്രതിമാസ വരുമാനം | Monthly Income', models.CharField(choices=[(1, 'തെരഞ്ഞെടുക്കുക | Select'), (2, 'below 10000 താഴെ'), (3, '10000 - 30000'), (4, '30000 - 60000'), (5, 'Above 60000 മുകളിൽ')], default='തെരഞ്ഞെടുക്കുക | Select', max_length=60)),
                ('വീട് | House', models.CharField(choices=[(1, 'തെരഞ്ഞെടുക്കുക | Select'), (2, 'സ്വന്തം വീട് | Own House'), (3, 'വാടകയ്ക്ക് | Rented')], default='തെരഞ്ഞെടുക്കുക | Select', max_length=60)),
                ('റഫറൻസ് | Reference', models.CharField(choices=[(1, 'തെരഞ്ഞെടുക്കുക | Select'), (2, 'W/o'), (3, 'S/o'), (4, 'D/o')], default='തെരഞ്ഞെടുക്കുക | Select', max_length=60)),
                ('വീടിന്റെ പേര് | House Name', models.CharField(default='', max_length=60)),
                ('വീട് / വാർഡ് നമ്പർ | House / Ward No', models.CharField(default='', max_length=60)),
                ('റോഡ് / സ്ട്രീറ്റ് പേര് | Road / Street Name', models.CharField(default='', max_length=60)),
                ('വില്ലേജ് / പോസ്റ്റ് ഓഫീസ് | Village / Post Office', models.CharField(default='', max_length=60)),
                ('താലൂക്ക് / ജില്ല | Taluk / District', models.CharField(default='', max_length=60)),
                ('സംസ്ഥാനം | State', models.CharField(default='', max_length=60)),
                ('പിൻ കോഡ് | Pincode', models.IntegerField(default=0)),
                ('പൗരതം | Citizenship', models.CharField(default='', max_length=60)),
                ('ആധാര്\u200d നമ്പര്\u200d | Aadhar Number', models.IntegerField(default=0)),
                ('റേഷന്\u200d കാര്\u200dഡ് | Ration Card', models.CharField(choices=[(1, 'തെരഞ്ഞെടുക്കുക | Select'), (2, 'മഞ്ഞ | Yellow'), (3, 'പിങ്ക് | Pink'), (4, 'നീല | Blue'), (5, 'വെള്ള | White'), (6, 'കാർഡ് ഇല്ല | No Card')], default='തെരഞ്ഞെടുക്കുക | Select', max_length=60)),
            ],
        ),
    ]
