# Generated by Django 3.2.6 on 2021-08-28 13:16

import datetime
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fam_name', models.CharField(default='', max_length=100, verbose_name='കുടുംബ പേര് | Family Name')),
                ('nofm', models.IntegerField(default=1, verbose_name='അംഗങ്ങളുടെ എണ്ണം | Number of members')),
            ],
            options={
                'verbose_name_plural': 'Families',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_01', models.CharField(default='', max_length=100, verbose_name='01. ഔദ്യോഗിക പേര് | Full Name')),
                ('q_02', models.TextField(blank=True, default='', max_length=200, verbose_name='02. വിളിപ്പേരുകൾ പേര് | Aliases / Nicknames')),
                ('q_03', models.CharField(choices=[('1', 'തിരഞ്ഞെടുക്കുക | Select'), ('2', 'പുരുഷന്\u200d | Male'), ('3', 'സ്ത്രീ | Female'), ('4', 'ഭിന്ന ലിംഗം | Other')], default='തിരഞ്ഞെടുക്കുക | Select', max_length=60, verbose_name='03. ലിംഗഭേദം | Gender')),
                ('q_04', models.DateField(default=datetime.date(1111, 11, 11), verbose_name='04. ജനന തിയതി | Date of Birth')),
                ('q_05', models.CharField(choices=[('1', 'തിരഞ്ഞെടുക്കുക | Select'), ('2', 'പിതാവ് | Father'), ('3', 'മാതാവ് | Mother'), ('4', 'ഭര്\u200dത്താവ് | Husband'), ('5', 'ഭാര്യ | Wife'), ('6', 'മകന്\u200d | Son'), ('7', 'മകള്\u200d | Daughter'), ('8', 'സഹോദരന്\u200d | Brother'), ('9', 'സഹോദരി | Sister')], default='തിരഞ്ഞെടുക്കുക | Select', max_length=60, verbose_name='05. ബന്ധം | Relation')),
                ('q_06', models.CharField(blank=True, default='', max_length=100, verbose_name="06. പിതാവിന്\u200dറെ പേര് | Father's Name")),
                ('q_07', models.CharField(blank=True, default='', max_length=100, verbose_name="07. മാതാവിന്\u200dറെ പേര് | Mother's Name")),
                ('q_08', models.CharField(blank=True, default='', max_length=100, verbose_name="08. ഗാർഡിയന്റെ പേര് | Guardian's Name")),
                ('q_09', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='09. മൊബൈല്\u200dഫോണ്\u200d നമ്പര്\u200d | Mobile Number')),
                ('q_10', models.EmailField(blank=True, default='', max_length=60, verbose_name='10. ഇ മെയില്\u200d അഡ്രസ്\u200c | Email Address')),
                ('q_11', models.CharField(choices=[('1', 'തെരഞ്ഞെടുക്കുക | Select'), ('2', '10-ന് താഴെ | Below 10th'), ('3', '10-ാം ക്ലാസ്സ് | 10th Class'), ('4', '12-ാം ക്ലാസ്സ് | 12th Class'), ('5', 'ഡിപ്ലോമ | Diploma'), ('6', 'ബിരുദം | Graduate'), ('7', 'പോസ്റ്റ് ഗ്രാജ്വേറ്റ് | Post Graduate'), ('8', 'ഡോക്ടറേറ്റ് | Doctorate')], default='തെരഞ്ഞെടുക്കുക | Select', max_length=60, verbose_name='11. ഉയർന്ന വിദ്യാഭ്യാസം | Highest Education')),
                ('q_12', models.CharField(choices=[('1', 'തെരഞ്ഞെടുക്കുക | Select'), ('2', 'അവിവാഹിതന്\u200d / അവിവാഹിത | Single'), ('3', 'വിവാഹിതന്\u200d / വിവാഹിത Married '), ('4', 'വിധവ / വിഭാര്യന്\u200d Widow / Widower'), ('5', 'Second marriage'), ('6', 'Third marriage')], default='തെരഞ്ഞെടുക്കുക | Select', max_length=60, verbose_name='12. വിവാഹ നില | Marital Status')),
                ('q_13', models.DateField(default=datetime.date(1111, 11, 11), verbose_name='13. വിവാഹ തിയതി | Date of Marriage')),
                ('q_14', models.CharField(choices=[('1', 'തെരഞ്ഞെടുക്കുക | Select'), ('2', 'ബാധകമല്ല | Not applicable'), ('3', 'ദിവസ കൂലി | Daily Wages'), ('4', 'ശുശ്രൂഷ | Ministry'), ('5', 'ഗവണ്\u200dമന്റ് ജോലി | Government service'), ('6', 'പ്രൈവറ്റ് ജോലി | Private firm'), ('7', 'വിദേശത്തു ജോലി | Overseas Job'), ('8', 'ബിസിനസ് | Business'), ('9', 'ക്യഷി | Agriculture / Plantation'), ('10', 'കന്നുകാലി കൃഷി | Animal farming'), ('11', 'ഡോക്ടര്\u200d | Doctor'), ('12', 'നേഴ്\u200cസ് | Nurse'), ('13', 'മെഡിക്കൽ (മറ്റുള്ളവ) | Medical (Others)'), ('14', 'അധ്യാപകന്\u200d | Teacher'), ('15', 'വക്കീൽ | Advocate'), ('16', 'എൻജിനിയർ | Engineer'), ('17', 'ബാങ്ക് ജോലി | Bank Employee'), ('18', 'ഡ്രൈവിംഗ് | Driving Job'), ('19', 'തൊഴിലുറപ്പ് | NREGA'), ('20', 'സ്വയം തൊഴില്\u200d | Self Employed'), ('21', 'വീട്ടമ്മ | Home maker'), ('22', 'വിശ്രമ ജീവിതം | Retired'), ('23', 'ജോലി ഇല്ല | Not working'), ('24', 'വിദ്യാർത്ഥി | Student'), ('25', 'മറ്റുള്ളവ | Others')], default='തെരഞ്ഞെടുക്കുക | Select', max_length=60, verbose_name='14. ജോലി / തൊഴില്\u200d | Job / Employment')),
                ('q_15', models.CharField(choices=[('1', 'തെരഞ്ഞെടുക്കുക | Select'), ('2', 'below 10000 താഴെ'), ('3', '10000 - 30000'), ('4', '30000 - 60000'), ('5', 'Above 60000 മുകളിൽ')], default='തെരഞ്ഞെടുക്കുക | Select', max_length=60, verbose_name='15. പ്രതിമാസ വരുമാനം | Monthly Income')),
                ('q_16', models.CharField(choices=[('1', 'തെരഞ്ഞെടുക്കുക | Select'), ('2', 'സ്വന്തം വീട് | Own House'), ('3', 'വാടകയ്ക്ക് | Rented')], default='തെരഞ്ഞെടുക്കുക | Select', max_length=60, verbose_name='16. വീട് | House')),
                ('q_17_01', models.CharField(choices=[('1', 'തെരഞ്ഞെടുക്കുക | Select'), ('2', 'W/o'), ('3', 'S/o'), ('4', 'D/o')], default='17a. തെരഞ്ഞെടുക്കുക | Select', max_length=60, verbose_name='റഫറൻസ് | Reference')),
                ('q_17_02', models.CharField(blank=True, default='', max_length=60, verbose_name='17b. വീടിന്റെ പേര് | House Name')),
                ('q_17_03', models.CharField(blank=True, default='', max_length=60, verbose_name='17c. വീട് / വാർഡ് നമ്പർ | House / Ward No')),
                ('q_17_04', models.CharField(blank=True, default='', max_length=60, verbose_name='17d. റോഡ് / സ്ട്രീറ്റ് പേര് | Road / Street Name')),
                ('q_17_05', models.CharField(blank=True, default='', max_length=60, verbose_name='17e. വില്ലേജ് / പോസ്റ്റ് ഓഫീസ് | Village / Post Office')),
                ('q_17_06', models.CharField(blank=True, default='', max_length=60, verbose_name='17f. താലൂക്ക് / ജില്ല | Taluk / District')),
                ('q_17_07', models.CharField(blank=True, default='', max_length=60, verbose_name='17g. സംസ്ഥാനം | State')),
                ('q_17_08', models.IntegerField(default=0, verbose_name='17h. പിൻ കോഡ് | Pincode')),
                ('q_18', models.CharField(blank=True, default='', max_length=60, verbose_name='18. പൗരതം | Citizenship')),
                ('q_19', models.IntegerField(default=0, verbose_name='19. ആധാര്\u200d നമ്പര്\u200d | Aadhar Number')),
                ('q_20', models.CharField(blank=True, choices=[('1', 'തെരഞ്ഞെടുക്കുക | Select'), ('2', 'മഞ്ഞ | Yellow'), ('3', 'പിങ്ക് | Pink'), ('4', 'നീല | Blue'), ('5', 'വെള്ള | White'), ('6', 'കാർഡ് ഇല്ല | No Card')], default='തെരഞ്ഞെടുക്കുക | Select', max_length=60, verbose_name='20. റേഷന്\u200d കാര്\u200dഡ് | Ration Card')),
                ('q_21', models.CharField(blank=True, choices=[('1', 'തെരഞ്ഞെടുക്കുക | Select'), ('2', 'ഉണ്ട് | Yes'), ('3', 'ഇല്ല | No')], default='തെരഞ്ഞെടുക്കുക | Select', max_length=60, verbose_name='21. പാസ്പോര്\u200dട്ട്\u200c | Passport')),
                ('q_22', models.DateField(default=datetime.date(1111, 11, 11), verbose_name='22. രക്ഷിക്കപ്പെട്ട തിയതി | Date of Salvation')),
                ('q_23', models.DateField(default=datetime.date(1111, 11, 11), verbose_name='23. സ്നാനപ്പെട്ട തിയതി | Date of Baptism')),
                ('q_24', models.TextField(blank=True, default='', max_length=200, verbose_name='24. ഈ വിശ്വാസത്തിലേക്ക് വന്നപ്പോഴത്തെ സഭ (മാതൃ സഭ) | Church in which you were saved (Parent Church)')),
                ('q_25', models.TextField(blank=True, default='', max_length=200, verbose_name='25. സ്നാനം നടത്തിയ സ്ഥാനീയ സഭ | Church in which you were baptized')),
                ('q_26', models.TextField(blank=True, default='', max_length=200, verbose_name='26. വിവാഹം നടത്തിയ സ്ഥാനീയ സഭ | Church in which you were married')),
                ('q_27', models.TextField(blank=True, default='', max_length=200, verbose_name='27. ഈ വിശ്വാസത്തിലേക്ക് വരുന്നതിന് മുന്\u200dപ് ഉണ്ടായിരുന്ന വിശ്വാസ പശ്ചാത്തലം | Previous Faith (if any)')),
                ('q_28', models.TextField(blank=True, default='', max_length=200, verbose_name="28. പിതാവിന്\u200dറെ വിശ്വാസ പശ്ചാത്തലം | Father's faith background")),
                ('q_29', models.TextField(blank=True, default='', max_length=200, verbose_name="29. മാതാവിന്\u200dറെ വിശ്വാസ പശ്ചാത്തലം | Mother's faith background")),
                ('q_30', models.TextField(blank=True, default='', max_length=200, verbose_name="30. മറ്റു സഭകളില്\u200d അംഗം ആയിരുന്നെങ്കില്\u200d ആ സഭയുടെ പേരും അവിടെ തുടര്\u200dന്ന വര്\u200dഷങ്ങളും | Prevous Assembly (if any) & the no. of years you've attended it")),
                ('q_31', models.TextField(blank=True, default='', max_length=300, verbose_name="31. നിലവിലെ അസംബ്ലിയിലെ അംഗമായി നിങ്ങൾ പലപ്പോഴും പങ്കെടുത്തിട്ടുള്ള മറ്റ് സഭയുടെ പേര് നൽകുക | Name other churches you've often attended being a member of the current assembly")),
                ('q_32_01', models.CharField(blank=True, default='', max_length=60, verbose_name='32a. ആശുപത്രി / വീടിന്റെ പേര് | Hospital / House Name')),
                ('q_32_02', models.CharField(blank=True, default='', max_length=60, verbose_name='32b. വീട് / വാർഡ് നമ്പർ | House / Ward No')),
                ('q_32_03', models.CharField(blank=True, default='', max_length=60, verbose_name='32c. റോഡ് / സ്ട്രീറ്റ് പേര് | Road / Street Name')),
                ('q_32_04', models.CharField(blank=True, default='', max_length=60, verbose_name='32d. വില്ലേജ് / പോസ്റ്റ് ഓഫീസ് | Village / Post Office')),
                ('q_32_05', models.CharField(blank=True, default='', max_length=60, verbose_name='32e. താലൂക്ക് / ജില്ല | Taluk / District')),
                ('q_32_06', models.CharField(blank=True, default='', max_length=60, verbose_name='32f. സംസ്ഥാനം | State')),
                ('q_32_07', models.IntegerField(default=0, verbose_name='32g. പിൻ കോഡ് | Pincode')),
                ('q_33', models.CharField(blank=True, default='', max_length=60, verbose_name='33. ഏതുതരം പ്രവർത്തനം | Kind of Operation')),
                ('q_34', models.CharField(blank=True, default='', max_length=60, verbose_name='34. നിങ്ങളുടെ ജനനം രജിസ്റ്റർ ചെയ്തിട്ടുണ്ടോ? | Is your birth registered')),
                ('q_35', models.TextField(blank=True, default='', max_length=60, verbose_name='35. ജനനം മുതൽ വൈകല്യങ്ങൾ | Disabilities from birth')),
                ('q_36', models.DateField(blank=True, default=datetime.date(1111, 11, 11), max_length=60, verbose_name='36. മരണപ്പെട്ട തിയതി | Date of death')),
                ('q_37', models.TextField(blank=True, default='', max_length=80, verbose_name='37. മരണ കാരണം | Cause of death')),
                ('q_38_01', models.CharField(blank=True, default='', max_length=60, verbose_name='38a. ആശുപത്രി / വീടിന്റെ പേര് | Hospital / House Name')),
                ('q_38_02', models.CharField(blank=True, default='', max_length=60, verbose_name='38b. വീട് / വാർഡ് നമ്പർ | House / Ward No')),
                ('q_38_03', models.CharField(blank=True, default='', max_length=60, verbose_name='38c. റോഡ് / സ്ട്രീറ്റ് പേര് | Road / Street Name')),
                ('q_38_04', models.CharField(blank=True, default='', max_length=60, verbose_name='38d. വില്ലേജ് / പോസ്റ്റ് ഓഫീസ് | Village / Post Office')),
                ('q_38_05', models.CharField(blank=True, default='', max_length=60, verbose_name='38e. താലൂക്ക് / ജില്ല | Taluk / District')),
                ('q_38_06', models.CharField(blank=True, default='', max_length=60, verbose_name='38f. സംസ്ഥാനം | State')),
                ('q_38_07', models.IntegerField(blank=True, default=0, verbose_name='38g. പിൻ കോഡ് | Pincode')),
                ('q_39', models.TextField(blank=True, default='', max_length=300, verbose_name='39. ശവസംസ്കാര ചടങ്ങ് സഭ കൈകാര്യം ചെയ്യുന്നു | Church handling the burial cerimony')),
                ('q_40', models.FileField(blank=True, default='', upload_to='survey/assets/', verbose_name='40. ഫോട്ടോ ഐഡി | Photo ID')),
                ('q_41', models.FileField(blank=True, default='', upload_to='survey/assets/', verbose_name='41. ജനനത്തിനുള്ള ഡോക്യുമെന്റ് പ്രൂഫ് | Document proof for birth')),
                ('q_42', models.FileField(blank=True, default='', upload_to='survey/assets/', verbose_name='42. വിലാസത്തിനുള്ള പ്രമാണ തെളിവ് | Document proof for address')),
                ('q_43', models.FileField(blank=True, default='', upload_to='survey/assets/', verbose_name='43. വിവാഹത്തിനുള്ള രേഖയുടെ തെളിവ് | Document proof for marriage')),
                ('q_44', models.FileField(blank=True, default='', upload_to='survey/assets/', verbose_name='44. മരണത്തിനുള്ള രേഖ തെളിവ് | Document proof for death')),
                ('fly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_name', to='survey.family', verbose_name='കുടുംബ പേര് | Family Name')),
            ],
            options={
                'verbose_name_plural': 'People',
            },
        ),
    ]
