# Generated by Django 3.2.6 on 2021-08-26 15:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='q_22',
            field=models.DateField(default=datetime.date(1111, 11, 11), verbose_name='രക്ഷിക്കപ്പെട്ട തിയതി | Date of Salvation'),
        ),
        migrations.AddField(
            model_name='survey',
            name='q_23',
            field=models.DateField(default=datetime.date(1111, 11, 11), verbose_name='സ്നാനപ്പെട്ട തിയതി | Date of Baptism'),
        ),
        migrations.AddField(
            model_name='survey',
            name='ഈ വിശ്വാസത്തിലേക്ക് വന്നപ്പോഴത്തെ സഭ (മാതൃ സഭ) | Church in which you were saved (Parent Church)',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='survey',
            name='പാസ്പോര്\u200dട്ട്\u200c | Passport',
            field=models.CharField(choices=[(1, 'തെരഞ്ഞെടുക്കുക | Select'), (2, 'ഉണ്ട് | Yes'), (3, 'ഇല്ല | No')], default='തെരഞ്ഞെടുക്കുക | Select', max_length=60),
        ),
    ]
