# Generated by Django 3.2.6 on 2021-08-27 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='02. വിളിപ്പേരുകൾ പേര് | Aliases / Nicknames',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='survey',
            name='24. ഈ വിശ്വാസത്തിലേക്ക് വന്നപ്പോഴത്തെ സഭ (മാതൃ സഭ) | Church in which you were saved (Parent Church)',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='survey',
            name='25. സ്നാനം നടത്തിയ സ്ഥാനീയ സഭ | Church in which you were baptized',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='survey',
            name='26. വിവാഹം നടത്തിയ സ്ഥാനീയ സഭ | Church in which you were married',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='survey',
            name='27. ഈ വിശ്വാസത്തിലേക്ക് വരുന്നതിന് മുന്\u200dപ് ഉണ്ടായിരുന്ന വിശ്വാസ പശ്ചാത്തലം | Previous Faith (if any)',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='survey',
            name="28. പിതാവിന്\u200dറെ വിശ്വാസ പശ്ചാത്തലം | Father's faith background",
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='survey',
            name="29. മാതാവിന്\u200dറെ വിശ്വാസ പശ്ചാത്തലം | Mother's faith background",
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='survey',
            name="30. മറ്റു സഭകളില്\u200d അംഗം ആയിരുന്നെങ്കില്\u200d ആ സഭയുടെ പേരും അവിടെ തുടര്\u200dന്ന വര്\u200dഷങ്ങളും | Prevous Assembly (if any) & the no. of years you've attended it",
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='survey',
            name="31. നിലവിലെ അസംബ്ലിയിലെ അംഗമായി നിങ്ങൾ പലപ്പോഴും പങ്കെടുത്തിട്ടുള്ള മറ്റ് സഭയുടെ പേര് നൽകുക | Name other churches you've often attended being a member of the current assembly",
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='survey',
            name='35. ജനനം മുതൽ വൈകല്യങ്ങൾ | Disabilities from birth',
            field=models.TextField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='survey',
            name='37. മരണ കാരണം | Cause of death',
            field=models.TextField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='survey',
            name='q_39',
            field=models.TextField(default='', max_length=300, verbose_name='39. ശവസംസ്കാര ചടങ്ങ് സഭ കൈകാര്യം ചെയ്യുന്നു | Church handling the burial cerimony'),
        ),
    ]
