# Generated by Django 3.2.6 on 2021-08-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20210826_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='ഈ വിശ്വാസത്തിലേക്ക് വരുന്നതിന് മുന്\u200dപ് ഉണ്ടായിരുന്ന വിശ്വാസ പശ്ചാത്തലം | Previous Faith (if any)',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='survey',
            name="പിതാവിന്\u200dറെ വിശ്വാസ പശ്ചാത്തലം | Father's faith background",
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='survey',
            name="മറ്റു സഭകളില്\u200d അംഗം ആയിരുന്നെങ്കില്\u200d ആ സഭയുടെ പേരും അവിടെ തുടര്\u200dന്ന വര്\u200dഷങ്ങളും | Prevous Assembly (if any) & the no. of years you've attended it",
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='survey',
            name="മാതാവിന്\u200dറെ വിശ്വാസ പശ്ചാത്തലം | Mother's faith background",
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='survey',
            name='വിവാഹം നടത്തിയ സ്ഥാനീയ സഭ | Church in which you were married',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='survey',
            name='സ്നാനം നടത്തിയ സ്ഥാനീയ സഭ | Church in which you were baptized',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='survey',
            name='ഈ വിശ്വാസത്തിലേക്ക് വന്നപ്പോഴത്തെ സഭ (മാതൃ സഭ) | Church in which you were saved (Parent Church)',
            field=models.CharField(default='', max_length=200),
        ),
    ]
