# Generated by Django 3.2.6 on 2021-08-27 02:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20210826_2122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='ഔദ്യോഗിക പേര് | Full Name',
            new_name='1. ഔദ്യോഗിക പേര് | Full Name',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='ഇ മെയില്\u200d അഡ്രസ്\u200c | Email Address',
            new_name='10. ഇ മെയില്\u200d അഡ്രസ്\u200c | Email Address',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='ഉയർന്ന വിദ്യാഭ്യാസം | Highest Education',
            new_name='11. ഉയർന്ന വിദ്യാഭ്യാസം | Highest Education',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='വിവാഹ നില | Marital Status',
            new_name='12. വിവാഹ നില | Marital Status',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='വിവാഹ തിയതി | Date of Marriage',
            new_name='13. വിവാഹ തിയതി | Date of Marriage',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='ജോലി / തൊഴില്\u200d | Job / Employment',
            new_name='14. ജോലി / തൊഴില്\u200d | Job / Employment',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='പ്രതിമാസ വരുമാനം | Monthly Income',
            new_name='15. പ്രതിമാസ വരുമാനം | Monthly Income',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='വീട് | House',
            new_name='16. വീട് | House',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='താലൂക്ക് / ജില്ല | Taluk / District',
            new_name='17b. വീടിന്റെ പേര് | House Name',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='പൗരതം | Citizenship',
            new_name='17c. വീട് / വാർഡ് നമ്പർ | House / Ward No',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='റോഡ് / സ്ട്രീറ്റ് പേര് | Road / Street Name',
            new_name='17d. റോഡ് / സ്ട്രീറ്റ് പേര് | Road / Street Name',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='വില്ലേജ് / പോസ്റ്റ് ഓഫീസ് | Village / Post Office',
            new_name='17e. വില്ലേജ് / പോസ്റ്റ് ഓഫീസ് | Village / Post Office',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='വീടിന്റെ പേര് | House Name',
            new_name='17f. താലൂക്ക് / ജില്ല | Taluk / District',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='വീട് / വാർഡ് നമ്പർ | House / Ward No',
            new_name='17g. സംസ്ഥാനം | State',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='ആധാര്\u200d നമ്പര്\u200d | Aadhar Number',
            new_name='17h. പിൻ കോഡ് | Pincode',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='സംസ്ഥാനം | State',
            new_name='18. പൗരതം | Citizenship',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='പിൻ കോഡ് | Pincode',
            new_name='19. ആധാര്\u200d നമ്പര്\u200d | Aadhar Number',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name="ഗാർഡിയന്റെ പേര് | Guardian's Name",
            new_name='2. വിളിപ്പേരുകൾ പേര് | Aliases / Nicknames',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='റേഷന്\u200d കാര്\u200dഡ് | Ration Card',
            new_name='20. റേഷന്\u200d കാര്\u200dഡ് | Ration Card',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='പാസ്പോര്\u200dട്ട്\u200c | Passport',
            new_name='21. പാസ്പോര്\u200dട്ട്\u200c | Passport',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='ഈ വിശ്വാസത്തിലേക്ക് വന്നപ്പോഴത്തെ സഭ (മാതൃ സഭ) | Church in which you were saved (Parent Church)',
            new_name='24. ഈ വിശ്വാസത്തിലേക്ക് വന്നപ്പോഴത്തെ സഭ (മാതൃ സഭ) | Church in which you were saved (Parent Church)',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='ഈ വിശ്വാസത്തിലേക്ക് വരുന്നതിന് മുന്\u200dപ് ഉണ്ടായിരുന്ന വിശ്വാസ പശ്ചാത്തലം | Previous Faith (if any)',
            new_name='25. സ്നാനം നടത്തിയ സ്ഥാനീയ സഭ | Church in which you were baptized',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name="പിതാവിന്\u200dറെ വിശ്വാസ പശ്ചാത്തലം | Father's faith background",
            new_name='26. വിവാഹം നടത്തിയ സ്ഥാനീയ സഭ | Church in which you were married',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name="മറ്റു സഭകളില്\u200d അംഗം ആയിരുന്നെങ്കില്\u200d ആ സഭയുടെ പേരും അവിടെ തുടര്\u200dന്ന വര്\u200dഷങ്ങളും | Prevous Assembly (if any) & the no. of years you've attended it",
            new_name='27. ഈ വിശ്വാസത്തിലേക്ക് വരുന്നതിന് മുന്\u200dപ് ഉണ്ടായിരുന്ന വിശ്വാസ പശ്ചാത്തലം | Previous Faith (if any)',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name="മാതാവിന്\u200dറെ വിശ്വാസ പശ്ചാത്തലം | Mother's faith background",
            new_name="28. പിതാവിന്\u200dറെ വിശ്വാസ പശ്ചാത്തലം | Father's faith background",
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='വിവാഹം നടത്തിയ സ്ഥാനീയ സഭ | Church in which you were married',
            new_name="29. മാതാവിന്\u200dറെ വിശ്വാസ പശ്ചാത്തലം | Mother's faith background",
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='സ്നാനം നടത്തിയ സ്ഥാനീയ സഭ | Church in which you were baptized',
            new_name="30. മറ്റു സഭകളില്\u200d അംഗം ആയിരുന്നെങ്കില്\u200d ആ സഭയുടെ പേരും അവിടെ തുടര്\u200dന്ന വര്\u200dഷങ്ങളും | Prevous Assembly (if any) & the no. of years you've attended it",
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='ബന്ധം | Relation',
            new_name='5. ബന്ധം | Relation',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name="പിതാവിന്\u200dറെ പേര് | Father's Name",
            new_name="6. പിതാവിന്\u200dറെ പേര് | Father's Name",
        ),
        migrations.RenameField(
            model_name='survey',
            old_name="മാതാവിന്\u200dറെ പേര് | Mother's Name",
            new_name="7. മാതാവിന്\u200dറെ പേര് | Mother's Name",
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='വിളിപ്പേരുകൾ പേര് | Aliases / Nicknames',
            new_name="8. ഗാർഡിയന്റെ പേര് | Guardian's Name",
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='മൊബൈല്\u200dഫോണ്\u200d നമ്പര്\u200d | Mobile Number',
            new_name='9. മൊബൈല്\u200dഫോണ്\u200d നമ്പര്\u200d | Mobile Number',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='ലിംഗഭേദം | Gender',
        ),
        migrations.AddField(
            model_name='survey',
            name='3. ലിംഗഭേദം | Gender',
            field=models.CharField(choices=[(1, 'തിരഞ്ഞെടുക്കുക | Select'), (2, 'പുരുഷന്\u200d | Male'), (3, 'സ്ത്രീ | Female'), (4, 'ഭിന്ന ലിംഗം | Other')], default='4. തിരഞ്ഞെടുക്കുക | Select', max_length=60),
        ),
        migrations.AddField(
            model_name='survey',
            name="31. നിലവിലെ അസംബ്ലിയിലെ അംഗമായി നിങ്ങൾ പലപ്പോഴും പങ്കെടുത്തിട്ടുള്ള മറ്റ് സഭയുടെ പേര് നൽകുക | Name other churches you've often attended being a member of the current assembly",
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='survey',
            name='32a. ആശുപത്രി / വീടിന്റെ പേര് | Hospital / House Name',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='survey',
            name='32b. വീട് / വാർഡ് നമ്പർ | House / Ward No',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='survey',
            name='32c. റോഡ് / സ്ട്രീറ്റ് പേര് | Road / Street Name',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='survey',
            name='32d. വില്ലേജ് / പോസ്റ്റ് ഓഫീസ് | Village / Post Office',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='survey',
            name='32e. താലൂക്ക് / ജില്ല | Taluk / District',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='survey',
            name='32f. സംസ്ഥാനം | State',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='survey',
            name='32g. പിൻ കോഡ് | Pincode',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='survey',
            name='q_22',
            field=models.DateField(default=datetime.date(1111, 11, 11), verbose_name='22. രക്ഷിക്കപ്പെട്ട തിയതി | Date of Salvation'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='q_23',
            field=models.DateField(default=datetime.date(1111, 11, 11), verbose_name='23. സ്നാനപ്പെട്ട തിയതി | Date of Baptism'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='റഫറൻസ് | Reference',
            field=models.CharField(choices=[(1, 'തെരഞ്ഞെടുക്കുക | Select'), (2, 'W/o'), (3, 'S/o'), (4, 'D/o')], default='17a. തെരഞ്ഞെടുക്കുക | Select', max_length=60),
        ),
    ]
