# Generated by Django 3.2.6 on 2021-08-27 02:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20210827_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='33. ഏതുതരം പ്രവർത്തനം | Kind of Operation',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='survey',
            name='34. നിങ്ങളുടെ ജനനം രജിസ്റ്റർ ചെയ്തിട്ടുണ്ടോ? | Is your birth registered',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='survey',
            name='35. ജനനം മുതൽ വൈകല്യങ്ങൾ | Disabilities from birth',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='survey',
            name='36. മരണപ്പെട്ട തിയതി | Date of death',
            field=models.DateField(default=datetime.date(1111, 11, 11), max_length=60),
        ),
        migrations.AddField(
            model_name='survey',
            name='37. മരണ കാരണം | Cause of death',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='survey',
            name='38a. ആശുപത്രി / വീടിന്റെ പേര് | Hospital / House Name',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='survey',
            name='38b. വീട് / വാർഡ് നമ്പർ | House / Ward No',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='survey',
            name='38c. റോഡ് / സ്ട്രീറ്റ് പേര് | Road / Street Name',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='survey',
            name='38d. വില്ലേജ് / പോസ്റ്റ് ഓഫീസ് | Village / Post Office',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='survey',
            name='38e. താലൂക്ക് / ജില്ല | Taluk / District',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='survey',
            name='38f. സംസ്ഥാനം | State',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='survey',
            name='38g. പിൻ കോഡ് | Pincode',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='survey',
            name='40. Photo ID',
            field=models.FileField(default='', upload_to='survey/assets/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='q_39',
            field=models.CharField(default='', max_length=80, verbose_name='39. ശവസംസ്കാര ചടങ്ങ് സഭ കൈകാര്യം ചെയ്യുന്നു | Church handling the burial cerimony'),
        ),
    ]
