# Generated by Django 3.2.6 on 2021-08-27 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_auto_20210827_0828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='ജനന തിയതി | Date of Birth',
            new_name='4. ജനന തിയതി | Date of Birth',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='40. Photo ID',
        ),
        migrations.AddField(
            model_name='survey',
            name='40. ഫോട്ടോ ഐഡി | Photo ID',
            field=models.FileField(default='', upload_to='survey/assets/'),
        ),
        migrations.AddField(
            model_name='survey',
            name='41. ജനനത്തിനുള്ള ഡോക്യുമെന്റ് പ്രൂഫ് | Document proof for birth',
            field=models.FileField(default='', upload_to='survey/assets/'),
        ),
        migrations.AddField(
            model_name='survey',
            name='42. വിലാസത്തിനുള്ള പ്രമാണ തെളിവ് | Document proof for address',
            field=models.FileField(default='', upload_to='survey/assets/'),
        ),
        migrations.AddField(
            model_name='survey',
            name='43. വിവാഹത്തിനുള്ള രേഖയുടെ തെളിവ് | Document proof for marriage',
            field=models.FileField(default='', upload_to='survey/assets/'),
        ),
        migrations.AddField(
            model_name='survey',
            name='44. മരണത്തിനുള്ള രേഖ തെളിവ് | Document proof for death',
            field=models.FileField(default='', upload_to='survey/assets/'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='3. ലിംഗഭേദം | Gender',
            field=models.CharField(choices=[(1, 'തിരഞ്ഞെടുക്കുക | Select'), (2, 'പുരുഷന്\u200d | Male'), (3, 'സ്ത്രീ | Female'), (4, 'ഭിന്ന ലിംഗം | Other')], default='തിരഞ്ഞെടുക്കുക | Select', max_length=60),
        ),
    ]
