# Generated by Django 3.2.6 on 2021-08-27 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_auto_20210827_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='40. Photo ID',
            field=models.FileField(default='', upload_to='survey/assets/'),
        ),
    ]
