# Generated by Django 3.2.6 on 2021-08-27 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_auto_20210827_0835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='1. ഔദ്യോഗിക പേര് | Full Name',
            new_name='01. ഔദ്യോഗിക പേര് | Full Name',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='2. വിളിപ്പേരുകൾ പേര് | Aliases / Nicknames',
            new_name='02. വിളിപ്പേരുകൾ പേര് | Aliases / Nicknames',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='4. ജനന തിയതി | Date of Birth',
            new_name='04. ജനന തിയതി | Date of Birth',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name="6. പിതാവിന്\u200dറെ പേര് | Father's Name",
            new_name="06. പിതാവിന്\u200dറെ പേര് | Father's Name",
        ),
        migrations.RenameField(
            model_name='survey',
            old_name="7. മാതാവിന്\u200dറെ പേര് | Mother's Name",
            new_name="07. മാതാവിന്\u200dറെ പേര് | Mother's Name",
        ),
        migrations.RenameField(
            model_name='survey',
            old_name="8. ഗാർഡിയന്റെ പേര് | Guardian's Name",
            new_name="08. ഗാർഡിയന്റെ പേര് | Guardian's Name",
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='9. മൊബൈല്\u200dഫോണ്\u200d നമ്പര്\u200d | Mobile Number',
            new_name='09. മൊബൈല്\u200dഫോണ്\u200d നമ്പര്\u200d | Mobile Number',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='3. ലിംഗഭേദം | Gender',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='5. ബന്ധം | Relation',
        ),
        migrations.AddField(
            model_name='survey',
            name='03. ലിംഗഭേദം | Gender',
            field=models.CharField(choices=[('1', 'തിരഞ്ഞെടുക്കുക | Select'), ('2', 'പുരുഷന്\u200d | Male'), ('3', 'സ്ത്രീ | Female'), ('4', 'ഭിന്ന ലിംഗം | Other')], default='തിരഞ്ഞെടുക്കുക | Select', max_length=60),
        ),
        migrations.AddField(
            model_name='survey',
            name='05. ബന്ധം | Relation',
            field=models.CharField(choices=[('1', 'തിരഞ്ഞെടുക്കുക | Select'), ('2', 'പിതാവ് | Father'), ('3', 'മാതാവ് | Mother'), ('4', 'ഭര്\u200dത്താവ് | Husband'), ('5', 'ഭാര്യ | Wife'), ('6', 'മകന്\u200d | Son'), ('7', 'മകള്\u200d | Daughter'), ('8', 'സഹോദരന്\u200d | Brother'), ('9', 'സഹോദരി | Sister')], default='തിരഞ്ഞെടുക്കുക | Select', max_length=60),
        ),
        migrations.AlterField(
            model_name='survey',
            name='11. ഉയർന്ന വിദ്യാഭ്യാസം | Highest Education',
            field=models.CharField(choices=[('1', 'തെരഞ്ഞെടുക്കുക | Select'), ('2', '10-ന് താഴെ | Below 10th'), ('3', '10-ാം ക്ലാസ്സ് | 10th Class'), ('4', '12-ാം ക്ലാസ്സ് | 12th Class'), ('5', 'ഡിപ്ലോമ | Diploma'), ('6', 'ബിരുദം | Graduate'), ('7', 'പോസ്റ്റ് ഗ്രാജ്വേറ്റ് | Post Graduate'), ('8', 'ഡോക്ടറേറ്റ് | Doctorate')], default='തെരഞ്ഞെടുക്കുക | Select', max_length=60),
        ),
        migrations.AlterField(
            model_name='survey',
            name='12. വിവാഹ നില | Marital Status',
            field=models.CharField(choices=[('1', 'തെരഞ്ഞെടുക്കുക | Select'), ('2', 'അവിവാഹിതന്\u200d / അവിവാഹിത | Single'), ('3', 'വിവാഹിതന്\u200d / വിവാഹിത Married '), ('4', 'വിധവ / വിഭാര്യന്\u200d Widow / Widower'), ('5', 'Second marriage'), ('6', 'Third marriage')], default='തെരഞ്ഞെടുക്കുക | Select', max_length=60),
        ),
        migrations.AlterField(
            model_name='survey',
            name='14. ജോലി / തൊഴില്\u200d | Job / Employment',
            field=models.CharField(choices=[('1', 'തെരഞ്ഞെടുക്കുക | Select'), ('2', 'ബാധകമല്ല | Not applicable'), ('3', 'ദിവസ കൂലി | Daily Wages'), ('4', 'ശുശ്രൂഷ | Ministry'), ('5', 'ഗവണ്\u200dമന്റ് ജോലി | Government service'), ('6', 'പ്രൈവറ്റ് ജോലി | Private firm'), ('7', 'വിദേശത്തു ജോലി | Overseas Job'), ('8', 'ബിസിനസ് | Business'), ('9', 'ക്യഷി | Agriculture / Plantation'), ('10', 'കന്നുകാലി കൃഷി | Animal farming'), ('11', 'ഡോക്ടര്\u200d | Doctor'), ('12', 'നേഴ്\u200cസ് | Nurse'), ('13', 'മെഡിക്കൽ (മറ്റുള്ളവ) | Medical (Others)'), ('14', 'അധ്യാപകന്\u200d | Teacher'), ('15', 'വക്കീൽ | Advocate'), ('16', 'എൻജിനിയർ | Engineer'), ('17', 'ബാങ്ക് ജോലി | Bank Employee'), ('18', 'ഡ്രൈവിംഗ് | Driving Job'), ('19', 'തൊഴിലുറപ്പ് | NREGA'), ('20', 'സ്വയം തൊഴില്\u200d | Self Employed'), ('21', 'വീട്ടമ്മ | Home maker'), ('22', 'വിശ്രമ ജീവിതം | Retired'), ('23', 'ജോലി ഇല്ല | Not working'), ('24', 'വിദ്യാർത്ഥി | Student'), ('25', 'മറ്റുള്ളവ | Others')], default='തെരഞ്ഞെടുക്കുക | Select', max_length=60),
        ),
        migrations.AlterField(
            model_name='survey',
            name='15. പ്രതിമാസ വരുമാനം | Monthly Income',
            field=models.CharField(choices=[('1', 'തെരഞ്ഞെടുക്കുക | Select'), ('2', 'below 10000 താഴെ'), ('3', '10000 - 30000'), ('4', '30000 - 60000'), ('5', 'Above 60000 മുകളിൽ')], default='തെരഞ്ഞെടുക്കുക | Select', max_length=60),
        ),
        migrations.AlterField(
            model_name='survey',
            name='16. വീട് | House',
            field=models.CharField(choices=[('1', 'തെരഞ്ഞെടുക്കുക | Select'), ('2', 'സ്വന്തം വീട് | Own House'), ('3', 'വാടകയ്ക്ക് | Rented')], default='തെരഞ്ഞെടുക്കുക | Select', max_length=60),
        ),
        migrations.AlterField(
            model_name='survey',
            name='20. റേഷന്\u200d കാര്\u200dഡ് | Ration Card',
            field=models.CharField(choices=[('1', 'തെരഞ്ഞെടുക്കുക | Select'), ('2', 'മഞ്ഞ | Yellow'), ('3', 'പിങ്ക് | Pink'), ('4', 'നീല | Blue'), ('5', 'വെള്ള | White'), ('6', 'കാർഡ് ഇല്ല | No Card')], default='തെരഞ്ഞെടുക്കുക | Select', max_length=60),
        ),
        migrations.AlterField(
            model_name='survey',
            name='21. പാസ്പോര്\u200dട്ട്\u200c | Passport',
            field=models.CharField(choices=[('1', 'തെരഞ്ഞെടുക്കുക | Select'), ('2', 'ഉണ്ട് | Yes'), ('3', 'ഇല്ല | No')], default='തെരഞ്ഞെടുക്കുക | Select', max_length=60),
        ),
        migrations.AlterField(
            model_name='survey',
            name='40. ഫോട്ടോ ഐഡി | Photo ID',
            field=models.FileField(blank=True, default='', upload_to='survey/assets/'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='41. ജനനത്തിനുള്ള ഡോക്യുമെന്റ് പ്രൂഫ് | Document proof for birth',
            field=models.FileField(blank=True, default='', upload_to='survey/assets/'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='42. വിലാസത്തിനുള്ള പ്രമാണ തെളിവ് | Document proof for address',
            field=models.FileField(blank=True, default='', upload_to='survey/assets/'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='43. വിവാഹത്തിനുള്ള രേഖയുടെ തെളിവ് | Document proof for marriage',
            field=models.FileField(blank=True, default='', upload_to='survey/assets/'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='44. മരണത്തിനുള്ള രേഖ തെളിവ് | Document proof for death',
            field=models.FileField(blank=True, default='', upload_to='survey/assets/'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='റഫറൻസ് | Reference',
            field=models.CharField(choices=[('1', 'തെരഞ്ഞെടുക്കുക | Select'), ('2', 'W/o'), ('3', 'S/o'), ('4', 'D/o')], default='17a. തെരഞ്ഞെടുക്കുക | Select', max_length=60),
        ),
    ]
